#!/bin/bash
echo "open email.txt to view the mail"
`echo -ne "From: $1 \nTo: $2 \nCC:$3 \nSubject: Subject 1 \n This email is generated by my shell script \nThanks and regards \nS4 CSE student u4cse16505\nAmritapuri" > email.txt`
